### ISSUE TITLE
All auto email images broken

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#346]
Emails sent out to users for verification, password change, etc, have images inside the html and they are all broken and don't show.

**Comment by Enubia** [comment]
![image](https://user-images.githubusercontent.com/44695100/138221765-19fecd40-8d0b-4f9b-a922-bf83f87d53a6.png)

looks fine for me, keep in mind that ```cid:whatever image you need``` is needed for nodemailer and isn't supported in the browser as far as I know
