### ISSUE TITLE
Send auto-email after Agency.isVerified==true

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#355]
I have a html template for the email but needs to be automated, so when db updates that agency is verified, it should automatically trigger to send the email to the accountManager

**Comment by stacysealky** [comment]
@Enubia @gnorbsl - I agree with Patric. We could add a slack hook and get notified when a new agency signs up. 
Also, I was initially thinking something like this system
1) we get notified when a new agency signs up
2) I or someone else would go into prod db and change isAgencyVerified to true
3) isAgencyVerified? sendAutoVerifiedEmail() : null



Currently, I do random check-ins for the prod db to see if anyone new signed up, then do the rest of this all manually, not a very smart way to do these things.

**Comment by Enubia** [comment]
Alright, than let's go with a slack notification system as this is more reasonable.

**Comment by stacysealky** [comment]
@Enubia sounds good! 👍🏻
