### ISSUE TITLE
Add Edit/Delete functionalities for wishcard/me

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#357]
Suggested by Jacob below
---------------------------
On a side note: If we have some time, I would suggest modifying wishcard/me/ a bit (add editing functionality for partners - I don't think we had the time do that last time 👍 )

There's a PUT route for updating wishcard status (from admin panel), so we can reuse that if needed.

**Comment by Jacobjeevan** [comment]
- Added edit/delete routes
   - Added edit form page to frontend
- Added respective tests

Open another branch to complete the following:

- TODO: Complete styling for wishcard edit form
- TODO: Complete styling for buttons on my wishes page
- TODO: add confirmation dialog for delete functionality
- TODO (potentially): add ability to edit wishcard image.

**Comment by Jacobjeevan** [comment]
@stacysealky 

https://github.com/donategifts/donategifts/tree/wishcardEditFrontend

- wishcard Edit form (all styles inherited from create wishcard form)
- added confirmation dialogue for delete
- TODO: Button styles (Edit, Delete buttons)
      -  I tried to copy over button styles (profile-button class) into utils sass file, didn't work though. I am not too sure why. Once that's done, this should be good, except for ability to edit wishcard image.
