### ISSUE TITLE
Allow textarea writing for custom messages in wishcards/:id

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#371]
We should consider adding the text area under the dropdown of "Send Messages", so the user can send a custom message to the kid/agency. 

I know we didn't have this due to security concerns, but we could add a layer of admin check or slack check before the message can be posted on the site.

- more details to be added soon

**Comment by Jacobjeevan** [comment]
Okay, so add a status field to messages then? (approved/unapproved).

- Repurpose existing POST route (/wishcards/message)
- Remove passing in default messages for GET wishcard By Id route
- Replace message drop down in WishcardFullPage with a text area
- Webhook to approve message

@Enubia @stacysealky

**Comment by Enubia** [comment]
status field and additionally leave the default messages we have in and add another option to the select like ```your custom message``` or something with a hint that this needs approval

**Comment by stacysealky** [comment]
Agree with @Enubia. We should keep dropdown messages and add this as an optional feature.
I will think of a design to accommodate both.

For now, if you can start the backend, that'd be great!

**Comment by Jacobjeevan** [comment]
@stacysealky Backend is done btw; I have added the text area to frontend (on wishcard/:id page - I saw that you were redesigning that).
