### ISSUE TITLE
profile edit features

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#398]
- [ ] profile photo upload, change, delete
- [ ] first name and last name change
- [ ] agency website change
- [ ] agency address change
- [ ] agency phone number change

**Comment by Enubia** [comment]
regarding agency changes, do we want them to update the info by themselves or make them create a data change request an we update it via the admin panel?

**Comment by stacysealky** [comment]
@Enubia very good point! yes, it should create a data change request and update via admin panel

**Comment by Jacobjeevan** [comment]
Hmm, then do we add another field to agency then, as a catch all for all agency related changes? @Enubia @stacysealky

**Comment by Enubia** [comment]
ya that would be a good idea probably, maybe we could also use a data change table with a reference to the agency?
this way we would have a history on what changed when

**Comment by Jacobjeevan** [comment]
Interesting idea, maybe bit overkill for now though (how many edits do we see happening?).

We are going to move from Mongo anyways, so could just keep it simple for now and design a history table after migration.

**Comment by Jacobjeevan** [comment]
- Profile pic edit

#395  includes uploading profile image (doesn't show up on frontend though; need to style that). That includes both a put and delete route for updating/deleting profile pic.

- User profile edit

So, we already have a modal to edit About me on profile page. Are we redesigning the profile page? If so, we could try consolidating that with editing user profile details.

- Agency profile edit

Likewise add an edit modal for editing agency user details.

**Comment by Jacobjeevan** [comment]
- Agency profile edit

Functionality is done (https://github.com/donategifts/donategifts/tree/profileEdit if you want to check). Styling is todo.
