### ISSUE TITLE
When wishcard status: "published", automate email send to agency user who owns that wishcard

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#422]
details TBD

**Comment by gnorbsl** [comment]
@stacysealky i need templates pls, thax

**Comment by Enubia** [comment]
@stacysealky what template should we use for this?

**Comment by Enubia** [comment]
@stacysealky once again asking for templates :D

**Comment by Enubia** [comment]
@stacysealky weekly reminder for templates

**Comment by stacysealky** [comment]
@Enubia Isn't this already completed or am I imagining things?

**Comment by Enubia** [comment]
I don't think so but I can be wrong here, I'll checking tomorrow and let you know

I only remember fixing the confirmation emails for the donations

**Comment by Enubia** [comment]
@stacysealky weekly template reminder
