### ISSUE TITLE
Reset Password link does not work

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#477]
Link example: http://email.mail.donate-gifts.com/c/eJxdjrFuxCAQRL_GdFiwrLG3oLgm_wHscmfJjk-GJL-fVcpIo5nRFKMnycdIboUQouG0LUSumD2BA_AePAS1ODegFWSV6peCjXhCd-b9mPn6zEPsc2-jz_U6zStFDgS5ZYcbgCyVakXv1lBCaRgJzZFeY7z7FB4TfKj-f-j01eXumu_c-891s9ZbugzNHEGUiK1bcrSIm7fkudnsUQI64ZLZ3Kn3Q-T7VM7nH6j-_gKc-kXG

Issue1 - The link is broken. 
Issue2 - Email picture assets are broken.
Issue3 - When link is clicked, it shows "This site cannot be reached" screen

**Comment by Enubia** [comment]
i don't know where you got this link from but it should be
donate-gifts.com/users/password/reset/{hash}

tested everything locally and worked just fine
