### ISSUE TITLE
Automate email - Donation Receipt to donor and partner

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#503]
This email was previously sending fine, but not working anymore. 

**Email to donor**
Template is in ~/server/resources/email/donorDonationReceipt.html 

- [ ] check donation data status and automatically send the email to donor after payment was successful 
- [ ] please change the alt text for img tags (they just say "image" or "I'm an image" currently lol)
- [ ] test in local
- [ ] test in prod

**Email to partner** 
Wishcard.belongsTo will have an id of agency partner who created the wish card
Template is in ~/server/resources/email/partnerDonationAlert.html 

- [ ] check donation data status and automatically send the email to agency partner
- [ ] please change the alt text for img tags (they just say "image" or "I'm an image" currently lol)
- [ ] test in local
- [ ] test in prod

**Comment by stacysealky** [comment]
@Enubia  did we complete this?

**Comment by Enubia** [comment]
> @Enubia did we complete this?

yes
