### ISSUE TITLE
add loading cards to community page

### ISSUE THREAD

**Issue by Enubia** [donategifts/donategifts#545]
right now the page is collapsed while the component is fetching the posts
create a loading card to preview instead of a blank screen
example https://codepen.io/chris__sev/pen/mdrzYQE

**Comment by swarajsahil** [comment]
you want to shimmer UI in page until posts is not loaded

**Comment by stacysealky** [comment]
> 

who's this?

**Comment by stacysealky** [comment]
> you want to shimmer UI in page until posts is not loaded

who's this?

**Comment by stacysealky** [comment]
> right now the page is collapsed while the component is fetching the posts create a loading card to preview instead of a blank screen example https://codepen.io/chris__sev/pen/mdrzYQE

This is good!!

**Comment by Enubia** [comment]
> right now the page is collapsed while the component is fetching the posts create a loading card to preview instead of a blank screen example [codepen.io/chris__sev/pen/mdrzYQE](https://codepen.io/chris__sev/pen/mdrzYQE)

the component was already created and can be found in (here)[/js/react/compontends/shared/LoadingCards.jsx]

**Comment by Enubia** [comment]
fixed with #560
