### ISSUE TITLE
TASK: resize and compress images

### ISSUE THREAD

**Issue by Enubia** [donategifts/donategifts#546]
most of our images are huge and not optimized at all
we don't need 4k/2k or even 1080p images
revisit all images and resize them

https://tiny-img.com/blog/best-image-size-for-website/

**Comment by Enubia** [comment]
This was about our static images and not user uploads, for those we should create a separate issue

**Comment by stacysealky** [comment]
> This was about our static images and not user uploads, for those we should create a separate issue

I know haha I will create a separate issue
