### ISSUE TITLE
SPIKE: Donations History Page needs a new UI design

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#562]
Currently it looks really terrible

<img width="1792" alt="Screenshot 2023-07-28 at 6 22 46 PM" src="https://github.com/donategifts/donategifts/assets/26069780/475de789-e1e7-42d2-b982-02c97fb5ee02">

Need to redesign to make the UI better

**Comment by stacysealky** [comment]
- remove order id from table view and show in the full receipt only

- donated to "childFirstName" -> link to their wish page

- show agency info

- convert the date string to something more readable (MM-DD-YYYY) ? something that's more standard
(i.e. May 17, 2023) 

- wait for the DB migration, when the order status changes, then update the order status on each row

- download receipt as PDF

**Comment by stacysealky** [comment]
use accordion to expand/collapse the row and show receipt details

receipt details include:
- price
- payment method ending with (optional - need to look into possibility with paypal and apple pay) 
- item name
- child name 
- agency name

**Comment by Jacobjeevan** [comment]
@stacysealky Hmm, do you mind creating a mock up for the accordion? (doesn't have to be anything detailed, something on paint will also work, just to get an idea of how things will be placed). What do you have in mind?
