### ISSUE TITLE
DEFECT: /profile page edit features not updating properly

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#575]
Fix /profile page edit features

- [ ] when user clicks the pencil icons in the /profile page, edit modals should populate, then after saving the data, it should update immediately.

**Comment by stacysealky** [comment]
Assigned to @nguyenit67

**Comment by nguyenit67** [comment]
do you assign deadline to us or we assign it ourselves

**Comment by Enubia** [comment]
@nguyenit67 no deadline specified, so take your time

**Comment by nguyenit67** [comment]
resolved frontend bug in #583

**Comment by nguyenit67** [comment]
@stacysealky the bug had been resolved in PR #585

**Comment by stacysealky** [comment]
@nguyenit67 - Can you please test this in dev server? https://donate-gifts-test.fly.dev/

**Comment by nguyenit67** [comment]
Kay, I will check it once I got home

**Comment by stacysealky** [comment]
@nguyenit67 I closed this one and moved it to 'done'.  I added a new issue #603
