### ISSUE TITLE
DEFECT: fix home buttons

### ISSUE THREAD

**Issue by Enubia** [donategifts/donategifts#601]
recent additions from #537 broke the home buttons as can be seen here

![image](https://github.com/donategifts/donategifts/assets/44695100/3a92506e-c976-4e92-a211-6e94e17e67e2)

please fix them and check what else is broken due to those changes

**Comment by stacysealky** [comment]
ok I tested in browser smallest width and it was fine, so I didn't catch this. 
Thanks for reporting @Enubia
