### ISSUE TITLE
TASK: validate wishItemURL from wishcard

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#605]
Page https://donate-gifts.com/wishcards/create

We will get the product details from the wishItemURL of WishCard Schema.

Example URL 1: https://www.amazon.com/dp/B09FPHSK74/ref=cm_gf_acsu_d_p0_e0_qd0_uaUeabH0QpVlPXTxWyIT?th=1
Example URL 2: https://www.amazon.com/Boxgear-Inseparable-Creative-Preschool-Activities/dp/B0CC31TKY2/ref=sr_1_5?keywords=toy&qid=1691540699&sr=8-5

Product ID: B09FPHSK74, B0CC31TKY2

String inside followed by "dp/" is the product ID. 

- [x] Task 1: validate string not empty
- [x] Task 2: validate string starts with "https://www.amazon.com/"
- [x] Task 3: validate that the product ID exists in the string - if productID is not found, reject submission!
- [x] Task 4: extract and save the productId separately when posting the wish card data object ---> first need to add "productID" field into the db/models/WishCard.ts

**Comment by Tokikko** [comment]
Il take this... (maybe)

**Comment by stacysealky** [comment]
> Il take this... (maybe)

Awesome, assigned!
