### ISSUE TITLE
DEFECT: message feature is broken and needs to be fixed

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#610]
Messaging from wishcard single page does not work anymore. 
Please investigate and fix the bug.

**Comment by stacysealky** [comment]
@Jacobjeevan 

When tested in [dev server,](https://donate-gifts-test.fly.dev/) message history does not display after sending the message


![Image](https://github.com/donategifts/donategifts/assets/26069780/9bdf1d26-d70f-4db7-b01d-d4f32e83d8f2)

**Comment by stacysealky** [comment]
Reopened issue after testing

**Comment by Jacobjeevan** [comment]
As mentioned in the meeting, the issue was for unverified users (I'll add a check to not display messaging feature for unverified users).

On a side note, got the custom messaging working https://github.com/donategifts/donategifts/tree/610-customMessaging
