### ISSUE TITLE
STORY: create a migration script from mongoDB -> postgres (remap seeder jsons)

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#616]
-Dependent on completion of #615 

- Use uuid for primary key
https://stackoverflow.com/questions/33274291/uuid-or-sequence-for-primary-key

- Change all constraints from integer to varchar(255)~

- Check the diagram to convert the seeder json data to match the new table definitions

https://dbdiagram.io/d/64ddb26d02bd1c4a5eea4e48

![image](https://github.com/donategifts/donategifts/assets/44695100/3c17b264-03df-4cdb-9ed3-eef9e3301d1b)

**Comment by Enubia** [comment]
> Use uuid for primary key
> Change all constraints from integer to varchar(255)

done in #615

**Comment by nick-w-nick** [comment]
> Check the diagram to convert the seeder json data to match the new table definitions

done in #678
