### ISSUE TITLE
TASK: change the font style of Community card title, convert to 3 columns

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#623]
<img width="1789" alt="Screenshot 2023-08-13 at 9 51 47 PM" src="https://github.com/donategifts/donategifts/assets/26069780/10e6427d-f250-4ba0-b05c-ae0e68e95d04">

<img width="560" alt="Screenshot 2023-08-13 at 9 54 05 PM" src="https://github.com/donategifts/donategifts/assets/26069780/2f055c5e-49b2-4451-9f3d-dbbb456681de">

- [ ] Community page card title font style should match the profile card title style
- [ ] Convert the 2 column style to 3 column UI with container-fluid

**Comment by stacysealky** [comment]
@Calvinsd - could you look into this issue?

**Comment by Calvinsd** [comment]
Yes sure.

**Comment by stacysealky** [comment]
@Tokikko - could you take this one? it's been left unresolved for a long time

**Comment by Tokikko** [comment]
Oki :)

**Comment by stacysealky** [comment]
@Tokikko  - if you haven't started this, let me know. I can take it.

**Comment by Tokikko** [comment]
I have not but i will(can) complete it during this week if you have other things to do

**Comment by stacysealky** [comment]
I tried the 3 column style but it looked strange so I made other minor UI improvements instead. Closing this issue now.
