### ISSUE TITLE
DEFECT: email verification broken

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#624]
Issue 1. Email verification link is broken and shows the 500 error page
<img width="1277" alt="Screenshot 2023-08-14 at 2 55 59 PM" src="https://github.com/donategifts/donategifts/assets/26069780/613f5309-8291-46fa-b311-751f59bf13e4">

Issue 2. Automated email has broken logo image
<img width="695" alt="Screenshot 2023-08-14 at 2 56 27 PM" src="https://github.com/donategifts/donategifts/assets/26069780/6fffd3a9-a058-42df-a08e-d840ac5ca6ce">

Issue 3. Need to add "Resend verification link" option for email verification, in case the first one didn't send or not working.
Please add another button under "Settings" card in profile page. 
We will redesign the settings section later, so for now just add the same button style.
Also, this button is only visible if user.isVerified === false
<img width="679" alt="Screenshot 2023-08-14 at 3 01 34 PM" src="https://github.com/donategifts/donategifts/assets/26069780/f0997b30-72b0-4380-af0f-a50e5f5519cc">

**Comment by stacysealky** [comment]
@Enubia - I saw your PR related to this issue. Could you complete all 3 steps listed in this issue?

**Comment by stacysealky** [comment]
@Jacobjeevan - Marco made a PR so please work on #670

**Comment by Enubia** [comment]
ya i think i only forgot to add the verification code resending part
we don't need to create a new one, just resend the one that's already existing

**Comment by Jacobjeevan** [comment]
Alright 👍

**Comment by stacysealky** [comment]
@Enubia  
this is still broken after testing it in prod
It either shows the 500 page when user is still logged in, or shows this below JSON message when user clicks the verification page and then logs in. Both cases, I was not able to proceed.

![Image](https://github.com/donategifts/donategifts/assets/26069780/5b81943f-c866-4422-bfa9-8d3d09b745c9)

**Comment by Enubia** [comment]
The verification it self works, I think what's happening here is that we do not correctly handle the mentioned cases. We should probably reload the user once he verifies himself and expire the link after some time so it cannot be used again
