### ISSUE TITLE
TASK: Wish page should show the item image if exists, else show placeholder

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#642]

**Comment by stacysealky** [comment]
@nguyenit67 This one is related to the wish card single page that you are working on. 
There are placeholder images in an array that Math.random() displays 1 image for the wish item (currently in pug).
Could you make sure that item image shows up if the user already uploaded it? 
Something like  `img src={wishItemImage || placeholderImage} `

**Comment by nguyenit67** [comment]
Sure
