### ISSUE TITLE
 Community page, creating post for non verified agencies 

### ISSUE THREAD

**Issue by Tokikko** [donategifts/donategifts#656]
Non verified agency is able to post community posts and they are immediately visible on community page after submission. 
Im not sure if we need to manually allow posts or not but at least posts for non verified agencies should not be returned. 
![image](https://github.com/donategifts/donategifts/assets/7117338/e8821ac2-aeb1-4da7-9997-53d8db1c2b80)

**Comment by stacysealky** [comment]
Ooh nice discovery! Thank you for reporting this @Tokikko
