### ISSUE TITLE
Prod Bug - cannot submit new wishcards 

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#660]
<img width="639" alt="Screenshot 2023-08-23 at 3 28 55 PM" src="https://github.com/donategifts/donategifts/assets/26069780/88384566-2b6e-40e7-b287-4fb327ac2172">
<img width="1217" alt="Screenshot 2023-08-23 at 3 33 52 PM" src="https://github.com/donategifts/donategifts/assets/26069780/84c394e5-bccc-42a9-b1db-71908c41864d">

**Comment by Enubia** [comment]
@stacysealky issue is resolved, test wasn't using AWS and thus no image was shown, @Tokikko fixed the post issue already
