### ISSUE TITLE
Test Server Bug- wish card image string not saved in DB

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#661]
on /wishcards/create page, wishcard image doesn't get stored in s3 and empty string is saved as the src.

<img width="481" alt="Screenshot 2023-08-23 at 4 04 00 PM" src="https://github.com/donategifts/donategifts/assets/26069780/3fe93358-99c0-413f-9078-8c6019fe8da0">
<img width="906" alt="Screenshot 2023-08-23 at 4 04 06 PM" src="https://github.com/donategifts/donategifts/assets/26069780/0f1322d3-bc2a-40d4-adb0-f4f5dce92e77">

**Comment by Tokikko** [comment]
As discussed the production has not been updated in few months and i do not have access to it so im reassigning the ticket to you :).

**Comment by stacysealky** [comment]
> As discussed the production has not been updated in few months and i do not have access to it so im reassigning the ticket to you :).

This one is not for prod. It's only happening in test server: https://donate-gifts-test.fly.dev/

**Comment by Tokikko** [comment]
Ah okay. Il need some info in pm.
