### ISSUE TITLE
TASK: convert the WishCardRepository 

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#670]
linked with #663 #617

**Comment by stacysealky** [comment]
@Jacobjeevan  hey can you take this ticket? Marco already completed the email verification defect, so we are switching things up a bit.

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan hey can you take this ticket? Marco already completed the email verification defect, so we are switching things up a bit.

Yep 👍
