### ISSUE TITLE
DEFECT: fix JSON message to display in toast 

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#675]
When new guest user accesses login and enters email/password that is incorrect, it goes to this screen. 
We should replace it with a nice toast message that's consistent with other toast displays.

<img width="1151" alt="Screenshot 2023-09-11 at 10 33 54 PM" src="https://github.com/donategifts/donategifts/assets/26069780/18c04621-e225-47b4-904e-e5eb1d27e398">

**Comment by Enubia** [comment]
this is already resolved, a toast message is displayed in case of incorrect data

and in case of not data the form can't be submitted
