### ISSUE TITLE
BACKLOG: S3 user uploaded images resizing

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#690]
s3 + lambda
when user uploads an image, resize it with a lambda function and then store it in s3 for performance optimization

**Comment by Enubia** [comment]
this is already happening when the agency upload the image

```ts
this.storage = multerS3({
				s3: new S3({
					accessKeyId: config.AWS.KEY,
					secretAccessKey: config.AWS.SECRET,
				}),
				Bucket: config.AWS.S3BUCKET,
				ACL: 'public-read',
				CacheControl: 'max-age=31536000',
				Key(_req, _file, cb) {
					cb(null, `${uuidv4()}.jpeg`);
				},
				resize: {
					height: 640,
				},
				toFormat: 'jpeg',
			});
```

**Comment by stacysealky** [comment]
> this is already happening when the agency uploads the image
> 
> ```ts
> this.storage = multerS3({
> 	s3: new S3({
> 		accessKeyId: config.AWS.KEY,
> 		secretAccessKey: config.AWS.SECRET,
> 	}),
> 	Bucket: config.AWS.S3BUCKET,
> 	ACL: 'public-read',
> 	CacheControl: 'max-age=31536000',
> 	Key(_req, _file, cb) {
> 		cb(null, `${uuidv4()}.jpeg`);
> 	},
> 	resize: {
> 		height: 640,
> 	},
> 	toFormat: 'jpeg',
> });
> ```

oh damn I forgot this existed! awesome, I'm closing the issue.
