### ISSUE TITLE
DEFECT: fix trailing semicolon on wishcards

### ISSUE THREAD

**Issue by Enubia** [donategifts/donategifts#698]
![image](https://github.com/donategifts/donategifts/assets/44695100/20d15420-c3b5-4b65-850b-db16a89b8a57)

**Comment by vd89** [comment]
Hey @Enubia 

Will like to work on the issue and fix it

**Comment by Enubia** [comment]
> Hey @Enubia
> 
> Will like to work on the issue and fix it

sure thing, I'll assign the issue to you
