### ISSUE TITLE
Fix the broken external links for agency partners (only some broken)

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#747]
On wishcards/single page, the agency website is broken in some cases. Please fix them.
<img width="1539" alt="Screenshot 2023-11-17 at 6 18 16 PM" src="https://github.com/donategifts/donategifts/assets/26069780/3acee242-aeaf-4646-9e49-fc9f130e10d3">

**Comment by DeanRTaylor1** [comment]
Hey, I'm working on this now.
