### ISSUE TITLE
Prod Defect List

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#748]
Please add more to this list if you find a defect in Prod. @Enubia @Tokikko 

- [x] #749
- [x] home page - hero buttons not stacking up in some mobile sizes (resolved)
- [x] #747 
- [x] #770

Screenshots below: 

home page - curated carousel cards showing as broken only in mobile
<img width="557" alt="Screenshot 2023-11-18 at 1 01 01 PM" src="https://github.com/donategifts/donategifts/assets/26069780/3d3f2bd0-dca2-4209-a4d4-3089a248179b">

**Comment by Tokikko** [comment]
https://donate-gifts.com/wishcards 
Not sure if its a bug but all wishcards are loaded at once and on slower networks it can take around 10 seconds to load (tested with throttling 4G speed in browser)

**Comment by stacysealky** [comment]
@Tokikko yeah we should make some enhancements on /wishcards page.
Post more defects if you find more! Thanks

**Comment by nick-w-nick** [comment]
@stacysealky Here are a few issues I've found in prod thus far:
#764 new donation not shown in donations list
#765 missing space between name and donation text
#766 broken image link in verification email

**Comment by stacysealky** [comment]
@Spacepro0 @DeanRTaylor1 @suresheerf 
Hey new members, if you find any new prod defect while testing, please add those defects here please 😺 
Thank you so much!!

**Comment by stacysealky** [comment]
> https://donate-gifts.com/wishcards 
> 
> Not sure if its a bug but all wishcards are loaded at once and on slower networks it can take around 10 seconds to load (tested with throttling 4G speed in browser)

resolved by #759
