### ISSUE TITLE
Convert terms.pug to terms.jsx

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#768]
For Terms of Service page https://donate-gifts.com/terms

Please convert the terms.pug to terms.jsx
Once converted, please replace the pug template with the new React page

Also, just as a reminder, we are adding NextJS soon, so please keep the newly converted pages under `/js/react/pages`
And we are keeping the page names camelCase to follow NextJS conventions.

**Comment by Spacepro0** [comment]
I am working on this.
