### ISSUE TITLE
Convert sign up page from Pug to React

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#773]
<img width="1451" alt="Screenshot 2023-11-23 at 11 52 27 PM" src="https://github.com/donategifts/donategifts/assets/26069780/8a7403df-f9c6-4949-8cfa-4a28c1932ba4">

**Comment by Spacepro0** [comment]
I am starting work on this issue.

**Comment by stacysealky** [comment]
> I am starting work on this issue.

Thank you 👍👍

**Comment by Spacepro0** [comment]
Should I also convert the `checkoutHelperModals.pug`?
