### ISSUE TITLE
Wishcards filter by agency does not scroll down in mobile screens

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts#847]
![image](https://github.com/donategifts/donategifts/assets/26069780/96016516-c008-40d5-bb43-23a0202bb085)

In desktop, it works fine but in mobile, it doesn't allow users to scroll down to the end of the select option list. It abruptly closes the search/filter panel when you try to do so.

**Comment by Jacobjeevan** [comment]
Hmm, only solution I've found is to disable close on clicking outside the menu (closeOnClickOutside to false). We can add a small close (x) button at the top as well ("Options" header block). What do you think @Enubia ?

**Comment by Enubia** [comment]
> Hmm, only solution I've found is to disable close on clicking outside the menu (closeOnClickOutside to false). We can add a small close (x) button at the top as well ("Options" header block). What do you think @Enubia ?

There's already a close button at the bottom

**Comment by Jacobjeevan** [comment]
> > Hmm, only solution I've found is to disable close on clicking outside the menu (closeOnClickOutside to false). We can add a small close (x) button at the top as well ("Options" header block). What do you think @Enubia ?
> 
> There's already a close button at the bottom

True, I thought it might be necessary to add another one at the top (scroll bar was scrolling to the bottom of the page first, but that only seems to be an issue in browser/inspect element mode; I checked my phone instead and it seems to be fine 👍  I'll just add the closeonClickOutside attribute).
